### PR TITLE
Deleted

### PR DESCRIPTION
**Pull request by NicolasAlmerge**
Deleted

### CODE REVIEW

**Comment by ptmcg** [comment]
`not not` in place of `bool()` is intentional, so please revert. Otherwise, I like the options.

**Comment by TheOneMusic** [comment]
Done, but why is it better?

**Comment by ptmcg** [comment]
Evaluated in-line instead of function call. Function calls in Python are expensive. I guess it is a micro-optimization, given all the other function calls going on with pyparsing, but this is an easy one, and you cut where you can.

Please address conflicts - I just renamed some classes.

(Are you still doing your Discord bot? Please email me ptmcg@austin.rr.com, I'd like to know how that is going.)

**Comment by TheOneMusic** [comment]
I see, thank you. I will open another PR and delete this one, it will be easier.

I'm still doing my bot, although I'm a student and don't find a lot of time for that (I didn't really code the bot for a while). Do you have a Discord account?

**Pull request closed without merging**
