### PR TITLE
First pass at tests from parser.runTests, with notes.

### PR DESCRIPTION
**Pull request by toonarmycaptain**
Fixture parser is in conftest.py.

### CODE REVIEW

**Comment by toonarmycaptain** [comment]
I took the tests from the basic [parser.runTests](https://github.com/pyparsing/plusminus/blob/e918fba06620cea2a444242061fcc7512a1582fa/test/arith_tests.py#L13-L108) and turned them into Pytest test cases. 

It might make sense to explicitly create test classes/functions for assigning vars, creating expressions/functions, evaluating expressions etc. I believe I only factored out the tests that seemed to group together by sharing context, or because they threw errors. The one exception being the case of calling `rnd()` in turn calling `random.random()`, it's result being non-deterministic, and possibly making the case for testing the operators individually or in groups (eg sin, cos, tan).

**Comment by toonarmycaptain** [comment]
@ptmcg This is just a straight pass at translating your long series of "eyeball-able" test cases into Pytest tests. Technically because of the variety of ops it probably validates a lot of the underlying parser, but more at the level of integration tests rather than comprehensive unit tests of individual operators. 

What do you think of the Pytest styling? What direction would you like to proceed?

**Comment by ptmcg** [comment]
Please create a separate test file for each class of parser in the example_parsers.py module. Import them using `from plusminus.examples.example_parsers import XXX`. The example parsers in that one module might actually themselves end up being in separate modules. If you want to prototype that up in a separate PR, go ahead.

**Comment by toonarmycaptain** [comment]
I'll see what I can do. :)

**Pull request closed without merging**
